- name: Copy file config to root ssh
  ansible.builtin.copy:
    src: config
    dest: /root/.ssh/config
    owner: root
    group: root
    mode: '0600'



- name: Synchronization rpmbuld using rsync protocol
  ansible.posix.synchronize:
    mode: pull
    src: rsync://repos.pip2scl.dk/usr/share/nginx/html/
    dest: /root/rpmbuild
  become: True