- name: Copy file config to root ssh
  ansible.builtin.copy:
    src: config
    dest: /root/.ssh/config
    owner: root
    group: root
    mode: '0600'

- name: Copy key file to root
  shell: cp /home/vagrant/scldistro /root/.ssh/id_rsa

- name: Set permissions
  ansible.builtin.file:
    path: /root/.ssh/id_rsa
    owner: root
    group: root
    mode: '0600'

#- name: Synchronization rpmbuld using rsync protocol
#  ansible.posix.synchronize:
#    mode: pull 
#   src: rsync://repos.pip2scl.dk/usr/share/nginx/html/
#   dest: /root/rpmbuild
# become: True
- name: Rsync oldfashined
  shell: rsync -avc repos.pip2scl.dk:/usr/share/nginx/html/* /root/rpmbuild/
  become: True